### ISSUE TITLE
SiteLogo

### ISSUE THREAD

**Issue by ascorbic** [aerian-studios/aerian-site-rebuild#4]
## Component Type:  Stateless

Check each box once you have completed done the task.

-   [ ] Component created
-   [ ] Styles written
-   [ ] Storybook created, with stories for all normal states
-   [ ] Tests written, with snapshot test at minimum
-   [ ] Code reviewed

Add PR link here when ready:

**Comment by S-unya** [comment]
@marekrodgersaerian what is the status of this? It looks like the site is correctly using a logo at the moment. @ascorbic is this something that you swept up in one of your big sweeps?

**Comment by S-unya** [comment]
It looks like it, closing ticket

**Comment by ascorbic** [comment]
git blame says it was you. It's not a separate component, just an img

**Comment by S-unya** [comment]
Stupid me or stupid blame?

**Comment by S-unya** [comment]
I think it is desireable to have a component, so re-opening.

**Comment by ascorbic** [comment]
https://github.com/aerian-studios/aerian-site-rebuild/commit/4bb4797d7726e10670416bb4e9e48632a428d27a#diff-c38c541d1d7f49d52ee065c5c13f519eR40
