### ISSUE TITLE
SocialGrid

### ISSUE THREAD

**Issue by ascorbic** [aerian-studios/aerian-site-rebuild#42]
## Component Type: Stateless

Check each box once you have completed done the task.

-   [x] Component created
-   [x] Styles written
-   [x] Storybook created, with stories for all normal states
-   [x] Tests written, with snapshot test at minimum
-   [ ] Code reviewed

Add PR link here when ready: #107

**Comment by S-unya** [comment]
@xgryph do you mind if I take over this? Do you have any code that you want to push?

**Comment by S-unya** [comment]
I'm not sure why CircleCI tests are not passing; they are run locally
