### ISSUE TITLE
FontAwesome icons are initially huge

### ISSUE THREAD

**Issue by ascorbic** [aerian-studios/aerian-site-rebuild#76]
**Describe the bug**
When the page loads, the social icons in the footer are > 1000px across. They return to correct size after the page finishes loading.

**To Reproduce**
1. Go to https://beta.aerian.com/
2. Watch footer
3. See Facebook icon is massive until page finishes loading
**Expected behavior**
Icons are normal size

**Comment by S-unya** [comment]
This is due to the use of `flex` also, another issue is that they are `<li>` elements not nested in `<ul>`s.

We could investigate using `grid` layout for these to solve this issue.
