### ISSUE TITLE
Fix footer contact

### ISSUE THREAD

**Issue by S-unya** [aerian-studios/aerian-site-rebuild#85]
Footer contat details have good Schema.org itemsProps, first itemProp on organisation is broken. Also, telephone could be an anchor for telephone ussage - e.g. `<a tel="12345">12345</a>`

**Comment by chris-bingham** [comment]
@S-unya 
Not sure I follow, I can't find a broken item prop?

Updated telephone to be an anchor tag with href="tel:1234"
