### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by ascorbic** [aerian-studios/aerian-site-rebuild#9]
## Component Type: Stateless 

Check each box once you have completed done the task.

-   [ ] Component created
-   [ ] Styles written
-   [ ] Storybook created, with stories for all normal states
-   [ ] Tests written, with snapshot test at minimum
-   [ ] Code reviewed

Add PR link here when ready:

**Comment by ascorbic** [comment]
@goodster If this is ready for team QA, could you add a pull request?

**Comment by goodster** [comment]
Will do @ascorbic
